name: Deploy to stage

on:
  pull_request:
    branches:
      - DEV
    types: [closed]

jobs:
  ftp-deploy:
    name: FTP Deploy to Stage
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 70.32.23.102
        username: ${{ secrets.FTP_USER_STAGE }}
        password: ${{ secrets.FTP_PASS_STAGE }}
        server-dir: /wp-content/plugins/ainsys-connector-content/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/node_modules/**
          **/src/**
          CHANGELOG.md
          README.md
          readme.txt